guards:
- additional_guard_config: null
  aws_model: null
  aws_region: null
  description: Track the number of tokens associated with the input to the LLM, and/or
    retrieved text from the vector database.
  google_model: null
  google_region: null
  intervention:
    action: report
    conditions:
    - comparand: 4096.0
      comparator: greaterThan
    message: This message was blocked due to moderation criteria.
    send_notification: false
  is_agentic: false
  name: Prompt Tokens
  ootb_type: token_count
  openai_api_base: null
  openai_api_key: null
  openai_deployment_id: null
  stage: prompt
  type: ootb
timeout_action: score
timeout_sec: 60
